using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PPTail.Data.FileSystem.Test
{
    // TODO: Replace with a mock generated by MOQ
    public class MockFileSystem : IFileSystem
    {
        public IEnumerable<String> Files { get; set;}

        public string FileText { get; set; }


        public IEnumerable<string> EnumerateFiles(string path)
        {
            return this.Files;
        }

        public string ReadAllText(string path)
        {
            return this.FileText;
        }
    }
}
