using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PPTail.Data.FileSystem.Test
{
    // TODO: Replace with a mock generated by MOQ
    public class MockFileSystem : IFileSystem
    {
        public IEnumerable<string> EnumerateFiles(string path)
        {
            throw new NotImplementedException();
        }

        public string ReadAllText(string path)
        {
            throw new NotImplementedException();
        }
    }
}
